apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-ocp
  namespace: demo-openshift-pipeline
spec:
  host: demo-web.apps.demo.sss.lab
  port:
    targetPort: 8080
  to:
    kind: Service
    name: demoocp-service
